export const titres = [
  'AFMA SA',
  'Afric Industries Sa',
  'Afriquia Gaz',
  'Agma Lahlou-Tazi',
  'Akdital',
  'Alliances',
  'Aluminum du Maroc',
  'Aradei Capital',
  'Atlanta',
  'Attijariwafa Bank',
  'Auto Hall',
  'Auto Nejma',
  'Balima',
  'BCP',
  'Bmce Bank',
  'Cartier Saada',
  'CDM',
  'CFG',
  'CIH',
  'Ciments Du Maroc',
  'Colorado',
  'Compagnie Sucrerie Marocaine',
  'CTM',
  'Dari Couspate',
  'Delattre Levivier Maroc',
  'Delta Holding S.A',
  'Disty Tech',
  'Disway',
  'Douja Prom Addoha',
  'Ennakl Automobiles SA',
  'Fenie Brossette',
  'Hps',
  'IB Maroc Com',
  'Introduction en Bourse',
  'Immorente Invest',
  'Involys',
  'Itissalat Al-Maghrib',
  'Jet Contractors',
  'Label Vie',
  'LafargeHolcim Maroc',
  'Les Eaux Minerales Oulmes',
  'Lesieur Cristal',
  'M2M Group',
  'Maghreb Oxygene',
  'Maghrebail',
  'Managem',
  'Maroc Leasing',
  'Marocaine pour le Commerce et l’Industrie Banque',
  'Marocaine Ste de Therapeutique',
  'Med Paper',
  'Micro Data SA',
  'Miniere Touissit',
  'Mutandis',
  'Nationale d’Electrolyse et de Petrochimie Ste',
  'Realis. Mecaniques',
  'Rebab Company',
  'Residences Dar Saada',
  'Risma',
  'S2M',
  'Salafin',
  'Sanlam Maroc',
  'SMI',
  'Societe des Boissons du Maroc',
  'Societe d’Exploitation des Ports',
  'Societe Equipement',
  'Ste de Travaux de Realisation d’Ouvrages et de Con',
  'Ste Nationale de Siderurgie',
  'Ste Promotion Pharmaceutique du Maghreb',
  'Stokvis Nord Afrique',
  'Taqa Morocco SA',
  'Timar',
  'Total Maroc SA',
  'Travaux Generaux De Construction',
  'Unimer',
  'Wafa Assurance',
  'Zellidja S.A',
];
